apiVersion: v1
kind: Pod
metadata:
  name: activemq
spec:
  hostNetwork: true
  containers:
    - name: activemq 
      image: rmohr/activemq
      env: 
        - name: ACTIVEMQ_HOST
      ports:
        - containerPort: 61616
  nodeSelector:
      disktype: sssd



