- hosts: localhost
  connection: local
  become: yes
  become_user: ubuntu
  tasks:
  - name: get ip of worker3
    shell: grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' hosts | awk 'FNR == 4 {print}' 
    register: workertwo    
  - name: Check if host is already copied to activemq.yml
    become: yes
    become_user: root
    shell: if grep -q {{workertwo.stdout}} activemq.yml; then     echo true; else     echo false; fi 
    register: check
  - name: copy host to activemq.yml 
    become: yes
    lineinfile:
      path: activemq.yml
      insertafter: 'ACTIVEMQ_HOST'
      line: '          value: {{workertwo.stdout}}'
      firstmatch: yes
      state: present
    when: check.stdout == 'false' 
- hosts: master
  become: yes
  become_user: root
  tasks: 
  - name: tranfer solr.yml to master
    copy: 
      src: solr.yml
      dest: solr.yml
  - name: tranfer activemq to master
    copy: 
      src: activemq.yml
      dest: activemq.yml
  - name: label worker3
    become: yes
    become_user: ubuntu
    shell: kubectl label nodes worker3 disktype=sssd  --overwrite=true
  - name: apply solr pod
    become: yes
    become_user: ubuntu
    shell: kubectl apply -f solr.yml
  - name: apply activemq (using default credentials)
    become: yes
    become_user: ubuntu
    shell: kubectl apply -f  activemq.yml 
