- hosts: localhost
  connection: local
  become: yes
  become_user: ubuntu
  tasks: 
    - name: Get ip of worker2 
      shell: grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' hosts | awk 'FNR == 3 {print}' 
      register: workertwo

- hosts: database 
  become: yes
  become_user: root
  tasks: 
    - name: install python-pymysql
      become: yes
      become_user: root
      shell: apt install mariadb-client-core-10.1 mysql-common mariadb-server-10.1 python3-mysqldb -y --force-yes
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: create misp mysql
      become: yes
      become_user: root
      mysql_db: 
        name: misp
        state: present 
    - name: create user root 
      become: yes
      become_user: root
      mysql_user: 
        name: root
        host: localhost
        password:
        priv: "*.*:ALL,GRANT"
        state: present
    - name: create user remote worker2
      become: yes
      become_user: root
      mysql_user: 
        name: root
        host: "{{ hostvars['localhost']['workertwo'].stdout }}"
        password: admin
        priv: '*.*:ALL'
        state: present
    - name: check if bind-address is aleready editet
      become: yes
      become_user: root
      shell: if grep -q  0.0.0.0  /etc/mysql/mariadb.conf.d/50-server.cnf; then     echo true; else     echo false; fi
      register: check      
    - name: edit /etc/mysql/mariadb.conf.d/50-server.cnf to allow remote access
      become: yes
      lineinfile: 
        path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
        regexp: "^bind-address" 
        line:  bind-address            = 0.0.0.0
        firstmatch: true
        state: present
      when: check.stdout == "false"
    - name: restart mysql
      become: yes
      become_user: root
      service:
        name: mysql 
        state: restarted
    - name: restart mysqld
      become: yes
      become_user: root
      service: 
        name: mysqld
        state: restarted



