- hosts: localhost
  connection: local
  become: yes
  become_user: ubuntu
  tasks: 
   - name: get ip for mysql host (database)
     become: yes
     become_user: root
     shell: grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' hosts | awk 'FNR == 5 {print}'
     register: databaseip   
   - name: check if MISPSetup.yml already editet
     become: yes
     become_user: root
     shell: if grep -q {{databaseip.stdout}} MISPSetup.yml; then     echo true; else     echo false; fi
     register: check  
   - name: edit MISPSetup.yml
     become: yes
     lineinfile:
       path: MISPSetup.yml
       insertafter: 'MYSQL_HOST'
       line: "          value: {{databaseip.stdout}}"
       firstmatch: yes
       state: present
     when: check.stdout == 'false'  

- hosts: master
  become: yes
  become_user: root
  tasks: 
    - name: label worker2
      become: yes
      become_user: ubuntu
      shell: kubectl label nodes worker2 disktype=ssd --overwrite=true
    - name: copy file to master
      copy: 
        src: MISPSetup.yml
        dest: MISPSetup.yml
    - name: Setting up MISP
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f MISPSetup.yml
