- hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks: 
   - name: get ip for misp baseurl 
     become: yes
     become_user: root
     shell: grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' hosts | awk 'FNR == 3 {print}'
     register: worker2   

- hosts: master
  become: yes
  become_user: ubuntu
  tasks:
    - name: change misp password
      become: yes
      become_user: ubuntu 
      shell: kubectl exec misp --  /var/www/MISP/app/Console/cake Password admin@admin.test Password1234
    - name: change misp password  
      become: yes
      become_user: ubuntu
      shell: kubectl exec misp --  /var/www/MISP/app/Console/cake Admin getAuthkey admin@admin.test | tail -1
      register: authkey
    - debug:
        var: authkey
        verbosity: 2 
    - name: change baseurl for misp
      become: yes
      become_user: ubuntu
      shell:  kubectl exec misp /var/www/MISP/app/Console/cake Baseurl  http://{{ hostvars['localhost']['worker2'].stdout }}
 
- hosts: localhost
  connection: local
  become: yes
  become_user: ubuntu
  tasks: 
   - name: check if key is already inserted
     become: yes
     become_user: root
     shell: if grep -q {{ hostvars['master']['authkey'].stdout }}  application.properties; then     echo true; else     echo false; fi
     register: check
   - name: insert MISP authkey into application.conf (TheHive)
     become: yes
     become_user: root
     replace:
       path: "application.properties"
       regexp: key = ""
       replace: key = "{{hostvars['master']['authkey'].stdout}}"
     when: check.stdout == 'false'
