apiVersion: v1
kind: Pod
metadata:
  name: misp
  labels:
    app: misp
spec:
  hostNetwork: true
  containers:
    - name: misp
      image: mhs98/misp
      env:
        - name: MYSQL_HOST
        - name: MYSQL_DATABASE
          value: "misp"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MISP_GPG_PASSWORD
          value: "ChangeThisDefaultPasswordXuJBao5Q2bps89LWFqWkKgDZwAFpNHvc"
        - name: MISP_ADMIN_EMAIL
          value: "admin@admin.test"
        - name: MISP_ADMIN_PASSPHRASE 
          value: "admin"
        - name: POSTFIX_RELAY_HOST
          value: "relay.fqdn"
        - name: "TIMEZONE"
          value: "Europe/Oslo"     
  nodeSelector:
     disktype: ssd
