apiVersion: v1
kind: Pod
metadata:
  name: solr
  labels:
    app: solr
spec:
  hostNetwork: true
  containers: 
    - name: solr
      image: solr
      ports:
      - containerPort: 8983    
  nodeSelector: 
     disktype: sssd
